name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # Ajusta esto si estás usando un generador de sitios estáticos o alguna otra herramienta

    - name: Build the project
      run: npm run build  # Ajusta esto según el comando que uses para construir tu sitio

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Ajusta esto al directorio que contiene tu sitio web generado
